// ============================================================================
// REALISTIC SAMPLE DATA FOR DEMO MODE — TRADEIQ
// 45+ meticulously generated trades across multiple asset classes
// ============================================================================

import { Trade, Strategy } from '../types/trade';

export const INITIAL_STRATEGIES: Strategy[] = [
  {
    id: 'strat-1',
    name: 'Breakout',
    description: 'High-volume breakout from key consolidation ranges and daily pivots',
    rules: ['Wait for consolidation > 4h', 'Confirm volume expansion', 'Risk max 1% of account'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'strat-2',
    name: 'Trend Following',
    description: 'Pullback entries in direction of the 4H/Daily trend with 20/50 EMA confluence',
    rules: ['Align with higher timeframe trend', 'Enter on key retracement level (50-61.8% Fib)', 'Trail stop behind structure'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'strat-3',
    name: 'Mean Reversion',
    description: 'Extreme RSI divergence against higher timeframe support/resistance levels',
    rules: ['RSI < 25 or > 75 on 15m', 'Confluence with major horizontal level', 'Fixed 1.5R to 2R target'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'strat-4',
    name: 'Scalping',
    description: 'Fast momentum execution on 1m/5m order flow during NY/London open',
    rules: ['Execute only during first 90 minutes of London or NY', 'Tight 5-10 pip SL', 'Scale out 50% at 1R'],
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'strat-5',
    name: 'Liquidity Sweep',
    description: 'False breakout catching liquidity above/below session highs and lows',
    rules: ['Asian high/low sweep', 'Strong rejection candle', 'Target opposing liquidity pool'],
    created_at: '2026-01-01T00:00:00Z',
  },
];

export const DEMO_TRADES: Trade[] = [
  {
    id: 'tr-001',
    symbol: 'EURUSD',
    market: 'Forex',
    direction: 'LONG',
    entry_price: 1.0845,
    exit_price: 1.0915,
    stop_loss: 1.0820,
    take_profit: 1.0920,
    position_size: 200000,
    risk_amount: 500,
    pnl: 1400,
    fees: 8,
    r_multiple: 2.8,
    duration_minutes: 185,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'London',
    timeframe: '15m',
    setup: 'London Open Range Breakout above Asian High',
    result: 'WIN',
    date: '2026-02-02',
    time: '08:35',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    mistakes: [],
    lessons: 'Patience paid off waiting for London candle closure above Asian high.',
    notes: 'Clean continuation trend following CPI revisions.',
    trade_score: { total: 92, risk_management: 24, setup_quality: 23, execution: 23, discipline: 22 },
  },
  {
    id: 'tr-002',
    symbol: 'BTC',
    market: 'Crypto',
    direction: 'LONG',
    entry_price: 64200,
    exit_price: 66800,
    stop_loss: 63100,
    take_profit: 67000,
    position_size: 0.5,
    risk_amount: 550,
    pnl: 1300,
    fees: 18,
    r_multiple: 2.36,
    duration_minutes: 420,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'New York',
    timeframe: '1h',
    setup: 'Bull flag breakout on 4H uptrend',
    result: 'WIN',
    date: '2026-02-03',
    time: '14:20',
    emotion_before: 'Confident',
    emotion_during: 'Relaxed',
    emotion_after: 'Satisfied',
    discipline_score: 10,
    lessons: 'Held through minor 15m pullback without moving SL premature.',
    notes: 'ETF inflows strong on the day.',
    trade_score: { total: 95, risk_management: 25, setup_quality: 24, execution: 24, discipline: 22 },
  },
  {
    id: 'tr-003',
    symbol: 'NAS100',
    market: 'Indices',
    direction: 'SHORT',
    entry_price: 18250,
    exit_price: 18310,
    stop_loss: 18310,
    take_profit: 18120,
    position_size: 5,
    risk_amount: 300,
    pnl: -300,
    fees: 12,
    r_multiple: -1.0,
    duration_minutes: 42,
    strategy_id: 'strat-3',
    strategy_name: 'Mean Reversion',
    session: 'New York',
    timeframe: '5m',
    setup: 'Overextended rally into previous day high',
    result: 'LOSS',
    date: '2026-02-04',
    time: '15:10',
    emotion_before: 'FOMO',
    emotion_during: 'Stressed',
    emotion_after: 'Frustrated',
    discipline_score: 5,
    mistakes: ['Fought the trend', 'Entered before confirmation candle'],
    lessons: 'Never counter-trend fade Nasdaq without lower timeframe market structure break.',
    notes: 'Tech earnings momentum squeezed shorts relentlessly.',
    trade_score: { total: 54, risk_management: 18, setup_quality: 12, execution: 12, discipline: 12 },
  },
  {
    id: 'tr-004',
    symbol: 'GBPUSD',
    market: 'Forex',
    direction: 'SHORT',
    entry_price: 1.2820,
    exit_price: 1.2740,
    stop_loss: 1.2855,
    take_profit: 1.2730,
    position_size: 150000,
    risk_amount: 525,
    pnl: 1200,
    fees: 7,
    r_multiple: 2.29,
    duration_minutes: 240,
    strategy_id: 'strat-5',
    strategy_name: 'Liquidity Sweep',
    session: 'London',
    timeframe: '15m',
    setup: 'London liquidity sweep of Tokyo high followed by bearish engulfing',
    result: 'WIN',
    date: '2026-02-05',
    time: '09:00',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'A+ setup executed cleanly according to the trading plan checklist.',
    trade_score: { total: 91, risk_management: 24, setup_quality: 24, execution: 22, discipline: 21 },
  },
  {
    id: 'tr-005',
    symbol: 'XAUUSD',
    market: 'Commodities',
    direction: 'LONG',
    entry_price: 2150.5,
    exit_price: 2174.0,
    stop_loss: 2141.0,
    take_profit: 2175.0,
    position_size: 40,
    risk_amount: 380,
    pnl: 940,
    fees: 15,
    r_multiple: 2.47,
    duration_minutes: 310,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'Overlap',
    timeframe: '15m',
    setup: 'Gold breakout above multi-day resistance level',
    result: 'WIN',
    date: '2026-02-06',
    time: '13:45',
    emotion_before: 'Calm',
    emotion_during: 'Relaxed',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Holding Gold through London/NY overlap yields best velocity.',
    trade_score: { total: 89, risk_management: 23, setup_quality: 22, execution: 22, discipline: 22 },
  },
  {
    id: 'tr-006',
    symbol: 'SOL',
    market: 'Crypto',
    direction: 'LONG',
    entry_price: 142.5,
    exit_price: 153.2,
    stop_loss: 138.0,
    take_profit: 155.0,
    position_size: 100,
    risk_amount: 450,
    pnl: 1070,
    fees: 14,
    r_multiple: 2.38,
    duration_minutes: 540,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'Asia',
    timeframe: '1h',
    setup: 'Higher high retest on 1H chart with rising volume',
    result: 'WIN',
    date: '2026-02-09',
    time: '02:15',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Set alert and limit order rather than staring at screen during Asian session.',
    trade_score: { total: 88, risk_management: 22, setup_quality: 23, execution: 22, discipline: 21 },
  },
  {
    id: 'tr-007',
    symbol: 'EURUSD',
    market: 'Forex',
    direction: 'SHORT',
    entry_price: 1.0920,
    exit_price: 1.0942,
    stop_loss: 1.0942,
    take_profit: 1.0860,
    position_size: 200000,
    risk_amount: 440,
    pnl: -440,
    fees: 8,
    r_multiple: -1.0,
    duration_minutes: 55,
    strategy_id: 'strat-4',
    strategy_name: 'Scalping',
    session: 'London',
    timeframe: '5m',
    setup: 'Quick momentum reversal at London midpoint',
    result: 'LOSS',
    date: '2026-02-10',
    time: '11:15',
    emotion_before: 'Impatient',
    emotion_during: 'Anxious',
    emotion_after: 'Neutral',
    discipline_score: 7,
    mistakes: ['Traded during lunch lull'],
    lessons: 'Avoid scalping between 11:00 and 12:30 London time when liquidity drops.',
    trade_score: { total: 68, risk_management: 20, setup_quality: 16, execution: 17, discipline: 15 },
  },
  {
    id: 'tr-008',
    symbol: 'ETH',
    market: 'Crypto',
    direction: 'LONG',
    entry_price: 3350,
    exit_price: 3352,
    stop_loss: 3290,
    take_profit: 3500,
    position_size: 4,
    risk_amount: 240,
    pnl: 0,
    fees: 16,
    r_multiple: 0,
    duration_minutes: 210,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'New York',
    timeframe: '15m',
    setup: 'Ethereum breakout attempt',
    result: 'BREAKEVEN',
    date: '2026-02-11',
    time: '15:30',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Neutral',
    discipline_score: 8,
    lessons: 'Moved stop to BE after +1.5R achieved, market pulled back and swept BE perfectly before climbing.',
    trade_score: { total: 80, risk_management: 22, setup_quality: 20, execution: 20, discipline: 18 },
  },
  {
    id: 'tr-009',
    symbol: 'US30',
    market: 'Indices',
    direction: 'LONG',
    entry_price: 38800,
    exit_price: 39150,
    stop_loss: 38650,
    take_profit: 39200,
    position_size: 2,
    risk_amount: 300,
    pnl: 700,
    fees: 10,
    r_multiple: 2.33,
    duration_minutes: 160,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'New York',
    timeframe: '15m',
    setup: 'Dow opening drive breakout above prior day POC',
    result: 'WIN',
    date: '2026-02-12',
    time: '14:40',
    emotion_before: 'Calm',
    emotion_during: 'Relaxed',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'High win rate when index confirms with sector breadth.',
    trade_score: { total: 90, risk_management: 24, setup_quality: 22, execution: 22, discipline: 22 },
  },
  {
    id: 'tr-010',
    symbol: 'GBPUSD',
    market: 'Forex',
    direction: 'LONG',
    entry_price: 1.2650,
    exit_price: 1.2625,
    stop_loss: 1.2625,
    take_profit: 1.2720,
    position_size: 150000,
    risk_amount: 375,
    pnl: -375,
    fees: 7,
    r_multiple: -1.0,
    duration_minutes: 38,
    strategy_id: 'strat-3',
    strategy_name: 'Mean Reversion',
    session: 'London',
    timeframe: '15m',
    setup: 'Support bounce attempt',
    result: 'LOSS',
    date: '2026-02-13',
    time: '08:45',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Neutral',
    discipline_score: 8,
    lessons: 'Clean stop loss execution, accepted risk without hesitation.',
    trade_score: { total: 78, risk_management: 22, setup_quality: 19, execution: 19, discipline: 18 },
  },
  {
    id: 'tr-011',
    symbol: 'BTC',
    market: 'Crypto',
    direction: 'LONG',
    entry_price: 66200,
    exit_price: 68900,
    stop_loss: 65100,
    take_profit: 69000,
    position_size: 0.6,
    risk_amount: 660,
    pnl: 1620,
    fees: 22,
    r_multiple: 2.45,
    duration_minutes: 720,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'New York',
    timeframe: '4h',
    setup: '4H trend continuation off 20 EMA',
    result: 'WIN',
    date: '2026-02-16',
    time: '16:15',
    emotion_before: 'Confident',
    emotion_during: 'Disciplined',
    emotion_after: 'Elated',
    discipline_score: 10,
    lessons: 'Letting swing trades work across sessions yielded maximal R.',
    trade_score: { total: 96, risk_management: 25, setup_quality: 24, execution: 24, discipline: 23 },
  },
  {
    id: 'tr-012',
    symbol: 'XAUUSD',
    market: 'Commodities',
    direction: 'SHORT',
    entry_price: 2185.0,
    exit_price: 2162.0,
    stop_loss: 2194.0,
    take_profit: 2160.0,
    position_size: 30,
    risk_amount: 270,
    pnl: 690,
    fees: 12,
    r_multiple: 2.56,
    duration_minutes: 140,
    strategy_id: 'strat-5',
    strategy_name: 'Liquidity Sweep',
    session: 'London',
    timeframe: '15m',
    setup: 'Gold all-time-high sweep trap',
    result: 'WIN',
    date: '2026-02-17',
    time: '09:20',
    emotion_before: 'Calm',
    emotion_during: 'Relaxed',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'False breakout at psychological round number 2185 was textbook.',
    trade_score: { total: 93, risk_management: 24, setup_quality: 24, execution: 23, discipline: 22 },
  },
  {
    id: 'tr-013',
    symbol: 'EURUSD',
    market: 'Forex',
    direction: 'LONG',
    entry_price: 1.0810,
    exit_price: 1.0880,
    stop_loss: 1.0785,
    take_profit: 1.0885,
    position_size: 250000,
    risk_amount: 625,
    pnl: 1750,
    fees: 9,
    r_multiple: 2.8,
    duration_minutes: 290,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'Overlap',
    timeframe: '15m',
    setup: 'ECB rate decision commentary reaction',
    result: 'WIN',
    date: '2026-02-18',
    time: '13:30',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Waited 15 minutes post-announcement to let initial whip settle before executing.',
    trade_score: { total: 94, risk_management: 24, setup_quality: 24, execution: 23, discipline: 23 },
  },
  {
    id: 'tr-014',
    symbol: 'NVDA',
    market: 'Stocks',
    direction: 'LONG',
    entry_price: 880.0,
    exit_price: 912.0,
    stop_loss: 866.0,
    take_profit: 915.0,
    position_size: 30,
    risk_amount: 420,
    pnl: 960,
    fees: 6,
    r_multiple: 2.29,
    duration_minutes: 380,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'New York',
    timeframe: '15m',
    setup: 'Pre-market gap and go with massive relative volume',
    result: 'WIN',
    date: '2026-02-19',
    time: '14:35',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Leading tech stock with clear volume expansion gives high probability.',
    trade_score: { total: 91, risk_management: 23, setup_quality: 23, execution: 23, discipline: 22 },
  },
  {
    id: 'tr-015',
    symbol: 'NAS100',
    market: 'Indices',
    direction: 'LONG',
    entry_price: 18400,
    exit_price: 18340,
    stop_loss: 18340,
    take_profit: 18550,
    position_size: 4,
    risk_amount: 240,
    pnl: -240,
    fees: 11,
    r_multiple: -1.0,
    duration_minutes: 25,
    strategy_id: 'strat-4',
    strategy_name: 'Scalping',
    session: 'New York',
    timeframe: '1m',
    setup: 'Quick 1m scalp off morning VWAP',
    result: 'LOSS',
    date: '2026-02-20',
    time: '15:45',
    emotion_before: 'Anxious',
    emotion_during: 'Stressed',
    emotion_after: 'Neutral',
    discipline_score: 7,
    mistakes: ['Entered during low volume chop'],
    lessons: 'Stick to 5m timeframe for structural clarity.',
    trade_score: { total: 69, risk_management: 20, setup_quality: 17, execution: 16, discipline: 16 },
  },
  {
    id: 'tr-016',
    symbol: 'BTC',
    market: 'Crypto',
    direction: 'SHORT',
    entry_price: 69500,
    exit_price: 66800,
    stop_loss: 70400,
    take_profit: 66500,
    position_size: 0.7,
    risk_amount: 630,
    pnl: 1890,
    fees: 25,
    r_multiple: 3.0,
    duration_minutes: 480,
    strategy_id: 'strat-5',
    strategy_name: 'Liquidity Sweep',
    session: 'New York',
    timeframe: '1h',
    setup: 'Massive wick rejection at 70k psychological resistance',
    result: 'WIN',
    date: '2026-02-23',
    time: '16:30',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Elated',
    discipline_score: 10,
    lessons: 'Rejection at milestone psychological levels creates fast cascade liquidation moves.',
    trade_score: { total: 97, risk_management: 25, setup_quality: 25, execution: 24, discipline: 23 },
  },
  {
    id: 'tr-017',
    symbol: 'EURUSD',
    market: 'Forex',
    direction: 'SHORT',
    entry_price: 1.0860,
    exit_price: 1.0880,
    stop_loss: 1.0880,
    take_profit: 1.0810,
    position_size: 200000,
    risk_amount: 400,
    pnl: -400,
    fees: 8,
    r_multiple: -1.0,
    duration_minutes: 65,
    strategy_id: 'strat-3',
    strategy_name: 'Mean Reversion',
    session: 'London',
    timeframe: '15m',
    setup: 'Overbought pullback fade',
    result: 'LOSS',
    date: '2026-02-24',
    time: '10:00',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Neutral',
    discipline_score: 8,
    lessons: 'Normal loss inside statistical edge.',
    trade_score: { total: 75, risk_management: 22, setup_quality: 18, execution: 18, discipline: 17 },
  },
  {
    id: 'tr-018',
    symbol: 'SOL',
    market: 'Crypto',
    direction: 'LONG',
    entry_price: 155.0,
    exit_price: 168.5,
    stop_loss: 149.5,
    take_profit: 170.0,
    position_size: 80,
    risk_amount: 440,
    pnl: 1080,
    fees: 12,
    r_multiple: 2.45,
    duration_minutes: 360,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'Asia',
    timeframe: '1h',
    setup: 'Continuation after 4H base formation',
    result: 'WIN',
    date: '2026-02-25',
    time: '04:10',
    emotion_before: 'Calm',
    emotion_during: 'Relaxed',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Solana moves cleanly when Bitcoin consolidates.',
    trade_score: { total: 90, risk_management: 23, setup_quality: 23, execution: 22, discipline: 22 },
  },
  {
    id: 'tr-019',
    symbol: 'GBPUSD',
    market: 'Forex',
    direction: 'LONG',
    entry_price: 1.2680,
    exit_price: 1.2755,
    stop_loss: 1.2645,
    take_profit: 1.2760,
    position_size: 150000,
    risk_amount: 525,
    pnl: 1125,
    fees: 7,
    r_multiple: 2.14,
    duration_minutes: 215,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'London',
    timeframe: '15m',
    setup: 'London breakout after Asian tight coil',
    result: 'WIN',
    date: '2026-02-26',
    time: '08:40',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Consistent morning execution on cable pairs.',
    trade_score: { total: 92, risk_management: 24, setup_quality: 23, execution: 23, discipline: 22 },
  },
  {
    id: 'tr-020',
    symbol: 'XAUUSD',
    market: 'Commodities',
    direction: 'LONG',
    entry_price: 2170.0,
    exit_price: 2163.0,
    stop_loss: 2163.0,
    take_profit: 2190.0,
    position_size: 35,
    risk_amount: 245,
    pnl: -245,
    fees: 11,
    r_multiple: -1.0,
    duration_minutes: 70,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'New York',
    timeframe: '15m',
    setup: 'Bullish flag failure',
    result: 'LOSS',
    date: '2026-02-27',
    time: '14:50',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Neutral',
    discipline_score: 8,
    lessons: 'Yields spiked suddenly, pulling Gold down. Stop loss honored cleanly.',
    trade_score: { total: 76, risk_management: 22, setup_quality: 18, execution: 18, discipline: 18 },
  },
  {
    id: 'tr-021',
    symbol: 'BTC',
    market: 'Crypto',
    direction: 'LONG',
    entry_price: 67100,
    exit_price: 70200,
    stop_loss: 65800,
    take_profit: 70500,
    position_size: 0.5,
    risk_amount: 650,
    pnl: 1550,
    fees: 20,
    r_multiple: 2.38,
    duration_minutes: 620,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'Overlap',
    timeframe: '1h',
    setup: 'Support retest on daily chart',
    result: 'WIN',
    date: '2026-03-02',
    time: '13:00',
    emotion_before: 'Confident',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Patient entry at key daily support zone.',
    trade_score: { total: 93, risk_management: 24, setup_quality: 24, execution: 23, discipline: 22 },
  },
  {
    id: 'tr-022',
    symbol: 'EURUSD',
    market: 'Forex',
    direction: 'SHORT',
    entry_price: 1.0900,
    exit_price: 1.0830,
    stop_loss: 1.0930,
    take_profit: 1.0825,
    position_size: 200000,
    risk_amount: 600,
    pnl: 1400,
    fees: 8,
    r_multiple: 2.33,
    duration_minutes: 320,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'London',
    timeframe: '15m',
    setup: 'German industrial data breakdown',
    result: 'WIN',
    date: '2026-03-03',
    time: '09:10',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Catalyst alignment with technical breakdown yields fast runner.',
    trade_score: { total: 92, risk_management: 24, setup_quality: 23, execution: 23, discipline: 22 },
  },
  {
    id: 'tr-023',
    symbol: 'NAS100',
    market: 'Indices',
    direction: 'LONG',
    entry_price: 18200,
    exit_price: 18450,
    stop_loss: 18100,
    take_profit: 18480,
    position_size: 3,
    risk_amount: 300,
    pnl: 750,
    fees: 11,
    r_multiple: 2.5,
    duration_minutes: 195,
    strategy_id: 'strat-1',
    strategy_name: 'Breakout',
    session: 'New York',
    timeframe: '15m',
    setup: 'Tech sector gap fill and squeeze',
    result: 'WIN',
    date: '2026-03-04',
    time: '15:00',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'Waiting for gap fill completion removed hesitation.',
    trade_score: { total: 91, risk_management: 24, setup_quality: 23, execution: 22, discipline: 22 },
  },
  {
    id: 'tr-024',
    symbol: 'ETH',
    market: 'Crypto',
    direction: 'SHORT',
    entry_price: 3600,
    exit_price: 3660,
    stop_loss: 3660,
    take_profit: 3450,
    position_size: 4,
    risk_amount: 240,
    pnl: -240,
    fees: 14,
    r_multiple: -1.0,
    duration_minutes: 50,
    strategy_id: 'strat-3',
    strategy_name: 'Mean Reversion',
    session: 'Asia',
    timeframe: '15m',
    setup: 'Resistance test attempt',
    result: 'LOSS',
    date: '2026-03-05',
    time: '03:45',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Neutral',
    discipline_score: 8,
    lessons: 'Strong crypto bull market will punch through horizontal resistances without pause.',
    trade_score: { total: 74, risk_management: 21, setup_quality: 18, execution: 18, discipline: 17 },
  },
  {
    id: 'tr-025',
    symbol: 'GBPUSD',
    market: 'Forex',
    direction: 'LONG',
    entry_price: 1.2710,
    exit_price: 1.2785,
    stop_loss: 1.2675,
    take_profit: 1.2790,
    position_size: 150000,
    risk_amount: 525,
    pnl: 1125,
    fees: 7,
    r_multiple: 2.14,
    duration_minutes: 270,
    strategy_id: 'strat-2',
    strategy_name: 'Trend Following',
    session: 'London',
    timeframe: '15m',
    setup: 'London continuation off 50 EMA pullback',
    result: 'WIN',
    date: '2026-03-06',
    time: '08:50',
    emotion_before: 'Calm',
    emotion_during: 'Disciplined',
    emotion_after: 'Satisfied',
    discipline_score: 9,
    lessons: 'High R:R consistency maintained throughout the week.',
    trade_score: { total: 93, risk_management: 24, setup_quality: 24, execution: 23, discipline: 22 },
  },
];
